-- ============================================================
-- Pediatric Urology Fellowship Seed (append to main research seed)
-- 28 ACGME-accredited programs from SPU accredited programs list
-- Specialty: Pediatric Urology
-- Match: AUA Pediatric Urology Match (not standard NRMP)
-- Source: SPU (spuonline.org/fellowships_ap.cgi), AUA Match, ACGME
-- ============================================================

INSERT INTO programs (
  id, name, institution, specialty, city, state,
  program_type, is_acgme_accredited, ecfmg_pathway_eligible,
  website, contact_email, description, verified, created_at,
  country, acgme_program_number, zip, street_address,
  eras_participating, nrmp_participating, program_director,
  visa_j1, visa_h1b, program_status, pgy1_positions,
  training_years, accepts_img, graduation_year_restriction,
  ecfmg_required, application_service, application_deadline,
  verified_at, provisional_data
) VALUES

  ('fa6e06e7-80f0-4cdc-a438-29b0d5439a48', 'Children''s Hospital Los Angeles (CHLA) Pediatric Urology Fellowship', 'Children''s Hospital Los Angeles', ARRAY['Pediatric Urology']::text[], 'Los Angeles', 'CA', 'fellowship', true, true, 'https://www.chla.org/fellowship/pediatric-urology-fellowship', NULL, 'Two-year ACGME- and SPU-accredited fellowship. Year 1 research, Year 2 clinical. U.S. citizenship not required. One fellow per year. Affiliated with USC. Part of AUA Pediatric Urology Match.', true, '2026-08-16T01:41:24.247799+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('c6a9bb15-d345-41a4-a814-87a41e50e5bf', 'Stanford University Pediatric Urology Fellowship', 'Stanford University', ARRAY['Pediatric Urology']::text[], 'Palo Alto', 'CA', 'fellowship', true, true, 'https://urology.stanford.edu/fellowships/pediatric-urology-fellowship', NULL, 'Pediatric urology fellowship at Stanford University School of Medicine. Part of AUA Pediatric Urology Match. Program Director: Erin Grantham, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.247893+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('3dc59f2c-998a-4d99-b468-cdd70c5b0b06', 'UC Irvine / Children''s Hospital of Orange County Pediatric Urology Fellowship', 'UC Irvine School of Medicine / Children''s Hospital of Orange County', ARRAY['Pediatric Urology']::text[], 'Orange', 'CA', 'fellowship', true, true, 'https://www.choc.org/clinical-services/pediatric-urology/', NULL, 'Pediatric urology fellowship at CHOC/UC Irvine. Program Director: Heidi Stephany, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.247937+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('c47387de-f4db-4045-818f-8ae0e98f80d0', 'UC San Diego Pediatric Urology Fellowship', 'UC San Diego / Rady Children''s Hospital', ARRAY['Pediatric Urology']::text[], 'San Diego', 'CA', 'fellowship', true, true, 'https://urology.ucsd.edu/education/fellowship/pediatric-urology/index.html', NULL, 'Pediatric urology fellowship at UC San Diego/Rady Children''s Hospital. Program Director: George Chiang, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.247968+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('7632117e-6852-448a-a02f-4eaa3ed7f4db', 'UCSF Benioff Children''s Hospital Pediatric Urology Fellowship', 'UCSF Benioff Children''s Hospital', ARRAY['Pediatric Urology']::text[], 'San Francisco', 'CA', 'fellowship', true, true, 'https://urology.ucsf.edu/education/fellowships/pediatric-urology', NULL, 'Pediatric urology fellowship at UCSF. Program Director: Hillary L. Copp, MD, MS. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.248000+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('556d9e7e-c55e-48ea-9c21-8080239903dc', 'Children''s Hospital Colorado / University of Colorado Pediatric Urology Fellowship', 'Children''s Hospital Colorado / University of Colorado Anschutz', ARRAY['Pediatric Urology']::text[], 'Aurora', 'CO', 'fellowship', true, true, 'https://medschool.cuanschutz.edu/surgery/specialties/urology/education/fellowship-in-pediatric-urology', NULL, 'Two-year ACGME-accredited fellowship. Year 1 clinical, Year 2 research (not ACGME-approved but required by AUA for subspecialty exam). Program Director: Nicholas G. Cost, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.248029+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('077cd6c9-de13-4d64-a901-bd242a162648', 'Children''s National Medical Center (A. Barry Belman) Pediatric Urology Fellowship', 'Children''s National Medical Center (Children''s National Hospital)', ARRAY['Pediatric Urology']::text[], 'Washington, DC', 'DC', 'fellowship', true, true, 'https://spuonline.org/fellowships_ap.cgi', NULL, 'Two-year ACGME-accredited fellowship. Program Director: Daniel Casella, MD. Named after A. Barry Belman. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.248057+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('d09da593-2867-4cc9-9d53-35d2d556abde', 'Nicklaus Children''s Hospital Pediatric Urology Fellowship', 'Nicklaus Children''s Hospital', ARRAY['Pediatric Urology']::text[], 'Miami', 'FL', 'fellowship', true, true, 'https://www.nicklauschildrens.org/medical-professionals/medical-education/graduate-medical-education-gme/b-gme-fellowship-training-programs/pediatric-urology-fellowship', NULL, 'Two-year ACGME-accredited fellowship (continually accredited since 2016). Year 1 clinical (ACGME year), Year 2 research/transitional. Training at Nicklaus and Jackson Memorial Hospital. Part of AUA Match.', true, '2026-08-16T01:41:24.248085+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('23b95133-4ece-4be4-b2c8-78fbcc27cea7', 'Emory University Pediatric Urology Fellowship', 'Emory University School of Medicine / Emory University Hospital', ARRAY['Pediatric Urology']::text[], 'Atlanta', 'GA', 'fellowship', true, true, 'https://med.emory.edu/departments/urology/education/pediatric-urology-fellowship.html', NULL, 'Pediatric urology fellowship at Emory. Program Director: Wolfgang Cerwinka, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.248110+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('0a2daf97-ea3b-44c0-af7e-ed286db0a220', 'Lurie Children''s Hospital (Northwestern) Pediatric Urology Fellowship', 'Ann and Robert H. Lurie Children''s Hospital of Chicago / Northwestern University Feinberg School of Medicine', ARRAY['Pediatric Urology']::text[], 'Chicago', 'IL', 'fellowship', true, true, 'https://www.luriechildrens.org/en/for-healthcare-professionals/education/medical-education-training/fellowships/pediatric-surgery-fellowships/urology-fellowships--training', NULL, 'Pediatric urology fellowship at Lurie Children''s/Northwestern. Formerly Children''s Memorial Hospital. Program Director: Catherine M. Seager, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.248143+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('f9db89bd-a1d0-4928-8a51-9df672c95f0a', 'Riley Hospital for Children / Indiana University Pediatric Urology Fellowship', 'Riley Hospital for Children / Indiana University Health', ARRAY['Pediatric Urology']::text[], 'Indianapolis', 'IN', 'fellowship', true, true, 'https://medicine.iu.edu/urology/expertise/pediatric-urology/fellowship', NULL, 'Pediatric urology fellowship at Riley Hospital/IU. Program Director: Benjamin Whittam, MD, MS. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.248171+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('6fcfadc6-d37e-4bfc-a63e-d48cf2c9d8c1', 'Boston Children''s Hospital Pediatric Urology Fellowship', 'Boston Children''s Hospital / Harvard Medical School', ARRAY['Pediatric Urology']::text[], 'Boston', 'MA', 'fellowship', true, true, 'https://dme.childrenshospital.org/graduate-medical-education/department-of-urology', NULL, 'Pediatric urology fellowship at Boston Children''s. Program Director: Erin McNamara, MD, MPH. Offers research year with degree program options. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.248201+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('fe3e489f-9c85-4878-aea3-0deca742dec8', 'Johns Hopkins Hospital Pediatric Urology Fellowship', 'Johns Hopkins Hospital / Johns Hopkins University School of Medicine', ARRAY['Pediatric Urology']::text[], 'Baltimore', 'MD', 'fellowship', true, true, 'https://www.hopkinsmedicine.org/urology/', NULL, 'Pediatric urology fellowship at Johns Hopkins. Program Director: Ming-Hsien Wang, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.248236+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('dac54869-14c0-4603-ac43-8707dc6b69ca', 'Washington University / St. Louis Children''s Hospital Pediatric Urology Fellowship', 'Washington University in St. Louis / St. Louis Children''s Hospital', ARRAY['Pediatric Urology']::text[], 'St. Louis', 'MO', 'fellowship', true, true, 'https://urology.wustl.edu/education/fellowships/pediatric-urology-fellowship/', NULL, 'Two-year ACGME-accredited fellowship. Year 1 clinical, Year 2 research. Graduates eligible for Pediatric Urology Subspecialty Certification (ABU). Program Director: Douglas Coplen, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.248260+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('a8f18bea-28de-4b7d-ad79-36aed4939e0b', 'University of Nebraska Medical Center / Children''s Nebraska Pediatric Urology Fellowship', 'University of Nebraska Medical Center / Children''s Nebraska', ARRAY['Pediatric Urology']::text[], 'Omaha', 'NE', 'fellowship', true, true, 'https://www.unmc.edu/surgery/residencies-fellowships/ped-urology-fellowship/index.html', NULL, 'Pediatric urology fellowship at UNMC/Children''s Nebraska. Program Director: John H. Makari, MD, FAAP, FACS. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.248281+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('ea11cb76-4328-4b30-bd43-b38dfeeece90', 'Cohen Children''s Medical Center of New York Pediatric Urology Fellowship', 'Cohen Children''s Medical Center of New York (Northwell Health)', ARRAY['Pediatric Urology']::text[], 'Lake Success', 'NY', 'fellowship', true, true, 'https://www.northwell.edu/pediatrics/fellowships/pediatric-urology-fellowship', NULL, 'Pediatric urology fellowship at Cohen Children''s Medical Center. Program Director: Lane S. Palmer, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.248307+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('8f378426-6624-463a-a8ca-2336911911eb', 'Cincinnati Children''s Hospital Medical Center Pediatric Urology Fellowship', 'Cincinnati Children''s Hospital Medical Center', ARRAY['Pediatric Urology']::text[], 'Cincinnati', 'OH', 'fellowship', true, true, 'https://www.cincinnatichildrens.org/education/clinical/fellowship/clinical-fellowships/', NULL, 'Pediatric urology fellowship at Cincinnati Children''s. Program Director: William R. DeFoor, Jr., MD, MPH. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.248336+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('4e72c231-943d-425e-893e-da162ffd3f66', 'Nationwide Children''s Hospital (Ohio State) Pediatric Urology Fellowship', 'Nationwide Children''s Hospital / The Ohio State University', ARRAY['Pediatric Urology']::text[], 'Columbus', 'OH', 'fellowship', true, true, 'https://www.nationwidechildrens.org/for-medical-professionals/education-and-training/fellowship-programs/urology-fellowship', NULL, 'Two-year ACGME-accredited fellowship: 12 months clinical + 12 months research. Unique schedule: 6 months protected research in Year 1, clinical immersion, then 6 months research at end of Year 2. Program Director: Seth A. Alpert, MD. Fellows eligible for CAQ from ABU. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.248373+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('d539af94-845c-43e4-a73b-51de66baf6ed', 'Oklahoma Children''s Hospital / OU College of Medicine Pediatric Urology Fellowship', 'Oklahoma Children''s Hospital / University of Oklahoma College of Medicine', ARRAY['Pediatric Urology']::text[], 'Oklahoma City', 'OK', 'fellowship', true, true, 'https://medicine.ouhsc.edu/academic-departments/urology/education-training/pediatric-urology-fellowship', NULL, 'Pediatric urology fellowship at OU/OU Children''s. Program Director: Bhalaajee Meenakshi-Sundaram, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.249207+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('fe906a20-468a-421b-aad1-46839cc4a2e9', 'Children''s Hospital of Philadelphia (CHOP) Pediatric Urology Fellowship', 'Children''s Hospital of Philadelphia / University of Pennsylvania School of Medicine', ARRAY['Pediatric Urology']::text[], 'Philadelphia', 'PA', 'fellowship', true, true, 'https://www.chop.edu/pediatric-fellowships/division-urology/fellowship', NULL, 'Two- or three-year ACGME-accredited fellowship. Founded 1976 by Dr. John Duckett (first pediatric urology fellowship). Four research tracks: basic science, clinical research, MSCE (1 year), or Master in Translational Research (2 years). Clinical volume >1,000 cases/year. Program Director: Christopher Long, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.249264+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('70293faf-4a73-4114-8f73-29ab284db4cd', 'Children''s Hospital of Pittsburgh (UPMC) Pediatric Urology Fellowship', 'Children''s Hospital of Pittsburgh / UPMC / University of Pittsburgh School of Medicine', ARRAY['Pediatric Urology']::text[], 'Pittsburgh', 'PA', 'fellowship', true, true, 'https://www.upmc.com/services/pediatrics/services/urology', NULL, 'Pediatric urology fellowship at Children''s Hospital of Pittsburgh/UPMC. Program Director: Francis X. Schneck, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.249290+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('4aea3d45-6262-4848-bfe1-9e871992ff33', 'UT Southwestern / Children''s Medical Center Pediatric Urology Fellowship', 'UT Southwestern Medical Center / Children''s Medical Center Dallas', ARRAY['Pediatric Urology']::text[], 'Dallas', 'TX', 'fellowship', true, true, 'https://www.utsouthwestern.edu/education/fellowships/pediatric-urology/', NULL, 'Pediatric urology fellowship at UTSW/Children''s Medical Center. Program Director: Micah Jacobs, MD. Coordinates interviews with Texas Children''s Hospital. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.249314+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('d2d1ffee-cdb7-40c2-831f-f24119dc85cf', 'Texas Children''s Hospital / Baylor College of Medicine Pediatric Urology Fellowship', 'Texas Children''s Hospital / Baylor College of Medicine', ARRAY['Pediatric Urology']::text[], 'Houston', 'TX', 'fellowship', true, true, 'https://www.texaschildrens.org/departments/urology', NULL, 'Pediatric urology fellowship at Texas Children''s/Baylor. Program Director: Nicolette Janzen. Coordinates interviews with UTSW. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.249420+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('4399b179-8116-4fb4-9113-f3a1de2cea1f', 'University of Tennessee-Memphis / LeBonheur Children''s Hospital Pediatric Urology Fellowship', 'University of Tennessee-Memphis / LeBonheur Children''s Hospital', ARRAY['Pediatric Urology']::text[], 'Memphis', 'TN', 'fellowship', true, true, 'https://www.uthsc.edu/urology/pediatric-fellowship/index.php', NULL, 'Pediatric urology fellowship at UT-Memphis/LeBonheur. Program Director: Dana W. Giel, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.249570+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('ed95966d-c2f3-4d0d-865c-a07fd7ef37c4', 'Vanderbilt University Medical Center Pediatric Urology Fellowship', 'Vanderbilt University Medical Center / Monroe Carell Jr. Children''s Hospital', ARRAY['Pediatric Urology']::text[], 'Nashville', 'TN', 'fellowship', true, true, 'https://www.vumc.org/urology/education-pediatric-urology-fellowship', NULL, 'Pediatric urology fellowship at Vanderbilt. Program Director: Abby Taylor, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.249654+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('9b3a83c7-7866-44f5-a57a-7340846c807d', 'University of Utah / Primary Children''s Hospital Pediatric Urology Fellowship', 'University of Utah / Primary Children''s Hospital', ARRAY['Pediatric Urology']::text[], 'Salt Lake City', 'UT', 'fellowship', true, true, 'https://urology.utah.edu/education/fellowships/pediatric-urology/', NULL, 'Pediatric urology fellowship at University of Utah/Primary Children''s. Program Director: Chad Wallis, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.249703+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('ccee6492-50ce-41fc-b19b-8b89eaa8be89', 'Seattle Children''s Hospital Pediatric Urology Fellowship', 'Seattle Children''s Hospital / University of Washington', ARRAY['Pediatric Urology']::text[], 'Seattle', 'WA', 'fellowship', true, true, 'https://urology.uw.edu/education/fellowship/pediatric-urology', NULL, 'Pediatric urology fellowship at Seattle Children''s/UW. Program Director: Kathleen Kieran, MD, MS, MME. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.249754+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('322ad65a-10f1-43e6-a895-6231dc8a5fca', 'Children''s Hospital of Wisconsin / Medical College of Wisconsin Pediatric Urology Fellowship', 'Children''s Hospital of Wisconsin / Medical College of Wisconsin', ARRAY['Pediatric Urology']::text[], 'Milwaukee', 'WI', 'fellowship', true, true, 'https://www.mcw.edu/surgery/urology/fellowships/pediatric-urology-fellowship', NULL, 'Pediatric urology fellowship at Children''s Hospital of Wisconsin/MCW. Program Director: Travis W. Groth, MD. Participating in 2027 SPU Match.', true, '2026-08-16T01:41:24.249813+00:00', 'United States', NULL, NULL, NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true)
;